export const types = {
  // Sync
  TASK_MANAGER_FILL_TASKS:      'TASK_MANAGER_FILL_TASKS',
  TASK_MANAGER_MARK_COMPLETE:   'TASK_MANAGER_MARK_COMPLETE',
  TASK_MANAGER_UNMARK_COMPLETE: 'TASK_MANAGER_UNMARK_COMPLETE',
  TASK_MANAGER_REMOVE:          'TASK_MANAGER_REMOVE',
  TASK_MANAGER_CREATE:          'TASK_MANAGER_CREATE',

  // Async
  TASK_MANAGER_FETCH_TASKS_ASYNC:     'TASK_MANAGER_FETCH_TASKS_ASYNC',
  TASK_MANAGER_MARK_COMPLETE_ASYNC:   'TASK_MANAGER_MARK_COMPLETE_ASYNC',
  TASK_MANAGER_UNMARK_COMPLETE_ASYNC: 'TASK_MANAGER_UNMARK_COMPLETE_ASYNC',
  TASK_MANAGER_REMOVE_ASYNC:          'TASK_MANAGER_REMOVE_ASYNC',
  TASK_MANAGER_CREATE_ASYNC:          'TASK_MANAGER_CREATE_ASYNC'
};
