export const types = {
  // Sync
  TASK_MANAGER_FILL_TASKS:      'TASK_MANAGER_FILL_TASKS',
  TASK_MANAGER_MARK_COMPLETE:   'TASK_MANAGER_MARK_COMPLETE',
  TASK_MANAGER_UNMARK_COMPLETE: 'TASK_MANAGER_UNMARK_COMPLETE',
  TASK_MANAGER_REMOVE:          'TASK_MANAGER_REMOVE',
  TASK_MANAGER_CREATE:          'TASK_MANAGER_CREATE',

  TASK_MANAGER_TRACK_ACTION:      'TASK_MANAGER_TRACK_ACTION',
  TASK_MANAGER_UNTRACK_ACTION:    'TASK_MANAGER_UNTRACK_ACTION',

  TASK_MANAGER_SHOW_CLIENT_ERROR:    'TASK_MANAGER_SHOW_CLIENT_ERROR',
  TASK_MANAGER_SHOW_SERVER_ERROR:    'TASK_MANAGER_SHOW_SERVER_ERROR',

  // Async
  TASK_MANAGER_FETCH_TASKS_ASYNC:     'TASK_MANAGER_FETCH_TASKS_ASYNC',
  TASK_MANAGER_MARK_COMPLETE_ASYNC:   'TASK_MANAGER_MARK_COMPLETE_ASYNC',
  TASK_MANAGER_UNMARK_COMPLETE_ASYNC: 'TASK_MANAGER_UNMARK_COMPLETE_ASYNC',
  TASK_MANAGER_REMOVE_ASYNC:          'TASK_MANAGER_REMOVE_ASYNC',
  TASK_MANAGER_CREATE_ASYNC:          'TASK_MANAGER_CREATE_ASYNC'
};
